(ns armate.archimate.metamodel.appendix-test
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.set :as o]
            [clojure.string :as s]
            [armate.archimate.metamodel.meta :as mt]
            [armate.archimate.metamodel.appendix :as adx]))

(def letters
  "scgirvantfo")

(def relationships-order
  [:specialization
   :composition
   :aggregation
   :assignment
   :realization
   :serving
   :access
   :influence
   :triggering
   :flow
   :association])

(def rels-letters-map
  (->> (map str letters)
       (zipmap relationships-order)))

(defn get-letters
  [from to]
  (let [general (get-in mt/general-relationships [from to])
        total (get-in adx/total-relationships [from to])]
    (->> (o/difference total #{:association_dir :access_r :access_w :access_rw})
         (sort-by #(.indexOf relationships-order %))
         (map (fn [relationship]
                (let [letter (rels-letters-map relationship)]
                  (if (general relationship)
                    (s/upper-case letter)
                    letter))))
         (s/join))))

(deftest total-relationships-test
  (testing "ArchiMate 3.2. Appendix B.5. Relationship Tables"
    (is (= "NO" (get-letters :motivation-driver :motivation-requirement)))
    (is (= "scgnO" (get-letters :motivation-goal :grouping)))
    (is (= "SCGNO" (get-letters :motivation-constraint :motivation-constraint)))
    (is (= "SCGNO" (get-letters :motivation-constraint :motivation-requirement)))
    (is (= "SCGNO" (get-letters :motivation-requirement :motivation-constraint)))
    (is (= "NO" (get-letters :motivation-requirement :motivation-driver)))
    (is (= "rNO" (get-letters :motivation-requirement :motivation-goal)))
    (is (= "SCGNO" (get-letters :motivation-requirement :motivation-requirement)))
    (is (= "O" (get-letters :motivation-requirement :business-process)))
    (is (= "O" (get-letters :motivation-requirement :application-component)))
    (is (= "scgrnO" (get-letters :motivation-requirement :grouping)))
    (is (= "NO" (get-letters :motivation-stakeholder :motivation-constraint)))
    (is (= "vtfO" (get-letters :strategy-capability :strategy-resource)))
    (is (= "O" (get-letters :strategy-capability :business-process)))
    (is (= "O" (get-letters :strategy-capability :business-product)))
    (is (= "vtfO" (get-letters :strategy-course-of-action :strategy-resource)))
    (is (= "O" (get-letters :strategy-course-of-action :business-process)))
    (is (= "O" (get-letters :strategy-course-of-action :application-component)))
    (is (= "scgrvntfO" (get-letters :strategy-course-of-action :grouping)))
    (is (= "IvtfO" (get-letters :strategy-resource :strategy-capability)))
    (is (= "O" (get-letters :strategy-resource :business-object)))
    (is (= "O" (get-letters :strategy-resource :business-process)))
    (is (= "rnO" (get-letters :business-actor :motivation-goal)))
    (is (= "RNO" (get-letters :business-actor :motivation-requirement)))
    (is (= "InO" (get-letters :business-actor :motivation-stakeholder)))
    (is (= "rO" (get-letters :business-actor :strategy-capability)))
    (is (= "aO" (get-letters :business-actor :business-object)))
    (is (= "vtfO" (get-letters :business-actor :business-product)))
    (is (= "vtfO" (get-letters :business-actor :application-component)))
    (is (= "vtfO" (get-letters :business-actor :application-service)))
    (is (= "vtfO" (get-letters :business-actor :technology-device)))
    (is (= "vtfO" (get-letters :business-actor :technology-process)))
    (is (= "aO" (get-letters :business-interface :business-object)))
    (is (= "aO" (get-letters :business-interface :business-contract)))
    (is (= "RNO" (get-letters :business-object :motivation-constraint)))
    (is (= "RNO" (get-letters :business-object :motivation-requirement)))
    (is (= "RO" (get-letters :business-object :strategy-resource)))
    (is (= "SCGO" (get-letters :business-object :business-object)))
    (is (= "SCGO" (get-letters :business-object :business-contract)))
    (is (= "O" (get-letters :business-object :application-data-object)))
    (is (= "O" (get-letters :business-object :business-representation)))
    (is (= "RNO" (get-letters :business-contract :motivation-constraint)))
    (is (= "RNO" (get-letters :business-contract :motivation-requirement)))
    (is (= "SCGO" (get-letters :business-contract :business-object)))
    (is (= "SCGO" (get-letters :business-contract :business-contract)))
    (is (= "O" (get-letters :business-contract :business-representation)))
    (is (= "CGvTFO" (get-letters :business-function :business-process)))
    (is (= "vtfO" (get-letters :business-role :location)))
    (is (= "scgirvantfO" (get-letters :business-role :grouping)))
    (is (= "RO" (get-letters :business-process :strategy-capability)))
    (is (= "O" (get-letters :business-process :strategy-resource)))
    (is (= "vtfO" (get-letters :business-process :business-actor)))
    (is (= "SCGvTFO" (get-letters :business-process :business-process)))
    (is (= "vtfO" (get-letters :business-process :application-process)))
    (is (= "RvtfO" (get-letters :business-process :business-service)))
    (is (= "vtfO" (get-letters :business-process :business-product)))
    (is (= "vtfO" (get-letters :business-process :application-service)))
    (is (= "aO" (get-letters :business-process :application-data-object)))
    (is (= "aO" (get-letters :business-process :technology-artifact)))
    (is (= "vtfO" (get-letters :business-process :technology-process)))
    (is (= "aO" (get-letters :business-process :physical-material)))
    (is (= "VtfO" (get-letters :business-service :business-process)))
    (is (= "vtfO" (get-letters :business-service :business-product)))
    (is (= "vtfO" (get-letters :business-service :application-service)))
    (is (= "vtfO" (get-letters :business-product :business-actor)))
    (is (= "CGaO" (get-letters :business-product :business-object)))
    (is (= "vtfO" (get-letters :business-product :business-role)))
    (is (= "CGaO" (get-letters :business-product :business-contract)))
    (is (= "CGrvtfO" (get-letters :business-product :business-service)))
    (is (= "CGaO" (get-letters :business-product :business-contract)))
    (is (= "SCGvtfO" (get-letters :business-product :business-product)))
    (is (= "CGaO" (get-letters :business-product :business-representation)))
    (is (= "CGaO" (get-letters :business-product :application-data-object)))
    (is (= "RO" (get-letters :business-representation :business-contract)))
    (is (= "RO" (get-letters :business-representation :business-object)))
    (is (= "O" (get-letters :business-representation :technology-artifact)))
    (is (= "rvtfO" (get-letters :application-collaboration :business-service)))
    (is (= "IrvtfO" (get-letters :application-collaboration :application-function)))
    (is (= "irvtfO" (get-letters :application-collaboration :application-service)))
    (is (= "rvtfO" (get-letters :application-component :business-service)))
    (is (= "SCGRvtfO" (get-letters :application-component :application-component)))
    (is (= "CgrvtfO" (get-letters :application-component :application-interface)))
    (is (= "irvtfO" (get-letters :application-component :application-service)))
    (is (= "aO" (get-letters :application-component :application-data-object)))
    (is (= "aO" (get-letters :application-component :technology-artifact)))
    (is (= "scgirvantfO" (get-letters :application-component :grouping)))
    (is (= "aO" (get-letters :application-interface :business-object)))
    (is (= "VtfO" (get-letters :application-interface :application-component)))
    (is (= "vtfO" (get-letters :application-interface :application-function)))
    (is (= "SCGvtfO" (get-letters :application-interface :application-interface)))
    (is (= "IvtfO" (get-letters :application-interface :application-service)))
    (is (= "RvtfO" (get-letters :application-function :business-function)))
    (is (= "aO" (get-letters :application-function :business-object)))
    (is (= "RvtfO" (get-letters :application-function :business-process)))
    (is (= "SCGvTFO" (get-letters :application-function :application-function)))
    (is (= "vtfO" (get-letters :application-function :application-interface)))
    (is (= "aO" (get-letters :application-function :technology-artifact)))
    (is (= "RNO" (get-letters :application-service :motivation-constraint)))
    (is (= "nO" (get-letters :application-service :motivation-driver)))
    (is (= "rnO" (get-letters :application-service :motivation-goal)))
    (is (= "VtfO" (get-letters :application-service :business-actor)))
    (is (= "aO" (get-letters :application-service :business-object)))
    (is (= "VtfO" (get-letters :application-service :business-process)))
    (is (= "RvtfO" (get-letters :application-service :business-service)))
    (is (= "VtfO" (get-letters :application-service :application-collaboration)))
    (is (= "VtfO" (get-letters :application-service :application-component)))
    (is (= "vtfO" (get-letters :application-service :application-interface)))
    (is (= "SCGvTFO" (get-letters :application-service :application-service)))
    (is (= "aO" (get-letters :application-service :technology-artifact)))
    (is (= "aO" (get-letters :application-service :physical-material)))
    (is (= "RO" (get-letters :application-data-object :business-object)))
    (is (= "O" (get-letters :application-data-object :business-product)))
    (is (= "O" (get-letters :application-data-object :technology-artifact)))
    (is (= "RO" (get-letters :technology-artifact :business-object)))
    (is (= "O" (get-letters :technology-artifact :business-representation)))
    (is (= "RO" (get-letters :technology-artifact :application-data-object)))
    (is (= "RO" (get-letters :technology-artifact :application-component)))
    (is (= "rO" (get-letters :technology-artifact :application-interface)))
    (is (= "SCGrO" (get-letters :technology-artifact :technology-artifact)))
    (is (= "O" (get-letters :technology-artifact :physical-material)))
    (is (= "RO" (get-letters :technology-artifact :technology-system-software)))
    (is (= "rvtfO" (get-letters :technology-device :business-process)))
    (is (= "vtfO" (get-letters :technology-device :technology-node)))
    (is (= "CGIrvtfO" (get-letters :technology-device :technology-system-software)))
    (is (= "VtfO" (get-letters :technology-interface :application-component)))
    (is (= "CGirvtfO" (get-letters :technology-node :technology-system-software)))
    (is (= "iaO" (get-letters :technology-node :technology-artifact)))
    (is (= "vtfO" (get-letters :technology-node :technology-path)))
    (is (= "rvtfO" (get-letters :technology-path :application-interface)))
    (is (= "GirvtfO" (get-letters :technology-path :technology-device)))
    (is (= "GivtfO" (get-letters :technology-path :technology-node)))
    (is (= "irvtfO" (get-letters :technology-path :technology-process)))
    (is (= "vtfO" (get-letters :technology-process :technology-node)))
    (is (= "vtfO" (get-letters :technology-process :technology-device)))
    (is (= "vtfO" (get-letters :technology-process :technology-system-software)))
    (is (= "O" (get-letters :technology-service :strategy-resource)))
    (is (= "rvtfO" (get-letters :technology-system-software :application-interface)))
    (is (= "rvtfO" (get-letters :technology-system-software :application-component)))
    (is (= "IaO" (get-letters :technology-system-software :technology-artifact)))
    (is (= "vtfO" (get-letters :technology-system-software :technology-device)))
    (is (= "vtfO" (get-letters :technology-system-software :technology-node)))
    (is (= "CgirvtfO" (get-letters :technology-system-software :technology-interface)))
    (is (= "iaO" (get-letters :technology-collaboration :technology-artifact)))
    (is (= "girvtfO" (get-letters :physical-distribution-network :technology-interface)))
    (is (= "IaO" (get-letters :physical-equipment :physical-material)))
    (is (= "irvtfO" (get-letters :physical-facility :business-process)))
    (is (= "IrvtfO" (get-letters :physical-facility :technology-process)))
    (is (= "iaO" (get-letters :physical-facility :physical-material)))
    (is (= "RO" (get-letters :physical-material :business-object)))
    (is (= "O" (get-letters :physical-material :business-representation)))
    (is (= "rO" (get-letters :physical-material :technology-artifact)))
    (is (= "rO" (get-letters :physical-material :technology-device)))
    (is (= "SCGrO" (get-letters :physical-material :physical-material)))
    (is (= "AO" (get-letters :implementation-event :implementation-deliverable)))
    (is (= "TfO" (get-letters :implementation-event :implementation-plateau)))
    (is (= "CGnO" (get-letters :location :motivation-driver)))
    (is (= "CGaO" (get-letters :location :business-representation)))
    (is (= "CGvtfO" (get-letters :location :technology-communication-network)))
    (is (= "CGrvtfO" (get-letters :location :technology-path)))
    (is (= "CGirvtfO" (get-letters :location :technology-system-software)))
    (is (= "CGvtfO" (get-letters :location :physical-distribution-network)))
    (is (= "SCGvtfO" (get-letters :location :location)))
    (is (= "sCGnO" (get-letters :grouping :motivation-driver)))
    (is (= "sCGirnO" (get-letters :grouping :motivation-stakeholder)))
    (is (= "sCGirvtfO" (get-letters :grouping :business-actor)))
    (is (= "sCGrvtfO" (get-letters :grouping :location)))
    (is (= "SCGirvantfO" (get-letters :grouping :grouping)))))
